/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "Auth": {
        "identityPoolId": "eu-west-2:e1f1f662-0c4a-46b4-b707-123a98e849f1",
        "region": "eu-west-2"
    }
};


export default awsmobile;
