name: Cypress Tests

on:
  pull_request:
    branches: [ main, staging ]
permissions:
  contents: read
  actions: read
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      REACT_APP_ENV: ${{ secrets.REACT_APP_ENV }}
      REACT_APP_SPOTIFY_CLIENT_ID: ${{ secrets.REACT_APP_SPOTIFY_CLIENT_ID }}
      REACT_APP_FEEDBACK_ENDPOINT: ${{ secrets.REACT_APP_FEEDBACK_ENDPOINT }}
      REACT_APP_PKCE_ENDPOINT: ${{ secrets.REACT_APP_PKCE_ENDPOINT }}
      REACT_APP_LOG_ENDPOINT: ${{ secrets.REACT_APP_LOG_ENDPOINT }}
      CI: true
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Install serve
        run: npm install -g serve

      - name: Start app
        run: serve -s build -l 3000 &
        
      - name: Wait for application to be ready
        run: npx wait-on http://localhost:3000 --timeout 60000

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          browser: chrome
          record: false

      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos